### DISCUSSION TITLE
Sending commands from HA to OTGW

### DISCUSSION THREAD

**Discussion by Aad3229** [rvdbreemen/OTGW-firmware#156] [Q&A] [answered]
I had the unavailable/shown problem. After flashing the latest firmware all values are visible in HA. The only problem left with MQTT is setting the setpoint from HA. From HA I publish "otgw/value//TrSet" (21.00) to the OTGW:

```
service: mqtt.publish
data:
  topic: otgw/value//TrSet
  retain: true
  payload: "{{ states('input_select.thermostaat_setpoint') }}"
```

(The value in "payload" = 21.00)

In the broker I briefly see the new value 21.00 at the subscribed topic but directly after that the TrSet returns to the original value (20.00) and the heater does nothing. 

I also tried the command: "otgw/set/TT=21.00" but nothing happens  

What am I doing wrong or what do I forget?
